### ISSUE TITLE
Add support for the "Matrix" protocol

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#294]
Could be interesting to add support for the Matrix protocol.

* https://matrix.org/docs/spec/client_server/r0.6.0
* https://matrix.org/docs/guides/implementing-more-advanced-e-2-ee-features-such-as-cross-signing
* https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide

**Comment by jhthorsen** [comment]
Adding this to Backlog and closing it. I won't focus on this right now.

**Comment by tboerger** [comment]
The current spec would be https://matrix.org/docs/spec/client_server/r0.6.0

**Comment by jhthorsen** [comment]
I don't know why I closed this. Should be enough to just add it to the backlog. 😢

**Comment by poVoq** [comment]
XMPP support would be even better. I am guessing a json interface would be easiest? See:
https://github.com/legastero/stanza

**Comment by tboerger** [comment]
Why would that be better? Maybe you should just create a new issue for that as it's a different protocol.

**Comment by poVoq** [comment]
Matrix server implementation is a mess, while xmpp is rock solid and works great. But yeah if there is any actual interest in other protocol than a new issue would make sense.

**Comment by marcusramberg** [comment]
Personally I found dealing with XMPP to be a mess. Not sure how a node library that exposes JS would help us with that. Anyways, if you want XMPP support, feel free to open another issue for that.

**Comment by poVoq** [comment]
That library can be used in pure client side javascript and basically abstracts away all the messy parts of xmpp's XML.

**Comment by jhthorsen** [comment]
@poVoq: Don’t ever pollute issues with unrelated comments. (It’s free to open new issues)

**Comment by jhthorsen** [comment]
Putting it in the fridge, since I don't see how I will find the time to implement this.
