### ISSUE TITLE
Should be able to handle "irc://..." links

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#311]
Not quite sure how to register links in the browser, but at least "irc://" links from within Convos should result in a new connection and a new dialog.

The first link to handle is the link in the text in convos-resources.vue:

> Wanna talk to us? Join the "#convos" channel on irc.freenode.net

**Comment by jacksgt** [comment]
Have you looked at [Web-based protocol handlers](Web-based protocol handlers)?

**Comment by jhthorsen** [comment]
Thanks for the link! It's exactly what I need on the client side. The difficult part is to create/find a connection and join a conversation.

**Comment by jhthorsen** [comment]
Different IRC URL formats:

* http://irc.lc/url
* http://archive.oreilly.com/pub/h/2018
* https://help.codeux.com/textual/IRC-URL-Scheme.kb
* http://www.mirc.com/mirclink.html

**Comment by RVRX** [comment]
Is there any documentation on how this feature is set up? I'm trying to register Convos as a valid handler of irc links in my browser as it didn't seem to do so automatically?

**Comment by jhthorsen** [comment]
This feature got removed when I converted from Vuejs to Svelte.

I’ll reopen this issue to get it back in.

**Comment by jhthorsen** [comment]
The UX is indeed terrible and not fixable, so I did this:

<img width="523" alt="Screen Shot 2021-07-18 at 10 06 27" src="https://user-images.githubusercontent.com/45729/126052578-5941acdf-643d-4917-848a-0dbe54dbd647.png">

The screenshot is from the "Account" page.
