### ISSUE TITLE
Status display - away from keyboard

### ISSUE THREAD

**Issue by ukcb** [convos-chat/convos#360]
The commands `/AWAY away from keyboard` and the reset with `/AWAY` work in principle, 
but they are not documented. Unfortunately no absence status is recognizable. 
Especially with persistent communication I would find a status display important.
Is this possibility planned? I don't like talking to people who are not present. :-)

**Comment by jhthorsen** [comment]
It could be cool if this was done one the server side after all the websocket connections where closed for a given user. If this would be implemented this way, then I think the user should be able to "opt out/in" from this feature.

I'm not sure if I remember correctly, but I think some users/networks doesn't appreciate people being AWAY. This could just be some misunderstanding from my side, but I would like to ask som IRC ops first.

**Comment by ukcb** [comment]
I'm mainly concerned with a simple status display, e.g. green symbol -> online, red symbol -> AWAY
The status should be easy to see.

**Comment by Wikiwide** [comment]
Would be nice if Convos Web UI automatically changed my status to /away when:
1) Convos tab isn't active;
or
2) Convos tab's window isn't active;
or
3) User has switched off the computer/logged out of session/switched user/locked the screen/blanked the screen/screensaver started.

And would be nice to see "away" status of other IRC users, too. In a compact way!

**Comment by jhthorsen** [comment]
I've added a reference from #444 to this issue, so I'm going to place this in the [fridge](https://github.com/Nordaaker/convos/milestone/20) until I start working on #444. 

Don't mind a PR though :)

**Comment by jhthorsen** [comment]
Going to reopen this, since I see that WHOIS does not respond with AWAY status.

Also have a look at https://bisqwit.iki.fi/jutut/away.html

**Comment by jhthorsen** [comment]
The AWAY message is now part of the WHOIS response, and the "/away" command is now supported.

TODO

- [ ] AWAY message is not stored, so it won't be set if you reconnect. Reason for that is that I simply don't know if this should per user or per connection. (I'm leaning toward per user)
- [ ] WHOIS is not run for private conversations, so there's no indication if the user is AWAY or not. (I'm not sure how to solve this either)
