### ISSUE TITLE
Normal/Voice users cannot change topic in channels missing cmode t.

### ISSUE THREAD

**Issue by RealKindOne** [convos-chat/convos#427]
1. Have another user /mode #channel -t
2. Click the hamburger with switches icon.
4. Put mouse over the topic box.
3. My mouse icon turns into the "no" icon.

**Expected behavior**

User should be able to edit the topic as the channel is missing cmode t.

[
![Screenshot_2019-12-27_20-39-57](https://user-images.githubusercontent.com/20209685/71537421-e30d1d80-28e9-11ea-8aea-f5189c3e6bb4.png)
](url)

**Comment by jhthorsen** [comment]
Is the channel mode set through Convos as well? Could it be that Convos doesn't support channel modes, but only user modes? (I'm thinking maybe the mode was never changed)

**Comment by jhthorsen** [comment]
Also, could you update the description with the command that is sent when trying to change topic? And what the error message is?

**Comment by RealKindOne** [comment]
I've updated my original post with more info.

**Comment by jhthorsen** [comment]
I didn't understand that the issue was just about the form in DialogSettings from the original description. Thanks for clearing that up.

Here is a copy of my response in irc.freenode.net/#convos:

> Yeah, the form assumes you need to be op. Convos does not track/care about what mode the channel has. This means fixing #427 is a bigger thing, that won't be done today

**Comment by jhthorsen** [comment]
This is fixed in v6.21.

https://github.com/convos-chat/convos/commit/b63431177c5425cba0bebbd147d61c54ca5b460c#diff-d30013f5174de3498205d84c7883aad7a4dfb97af4f4b7d1a97fb421a6d2fe82R67-R69
