### ISSUE TITLE
Mobile app for convos (iOS and Android)

### ISSUE THREAD

**Issue by BobWs** [convos-chat/convos#493]
Are there mobile apps to use with convos? iOS and Android

**Comment by marcusramberg** [comment]
No native apps at the moment, but Convos works pretty well both on ios and android as a PWA.

**Comment by rabbiveesh** [comment]
Is there any thought of making a cordova app out of it or something? I would actually like that.

**Comment by marcusramberg** [comment]
I was considering it but ran out of tuits. Contributions welcome.

**Comment by jhthorsen** [comment]
Note to self: https://svelte-native.technology/

**Comment by ElvishJerricco** [comment]
Why was this closed?

**Comment by jhthorsen** [comment]
I'm not sure to be honest. Maybe @BobWs lost interest?

I haven't created a new issue, since I don't have time to look at it atm. I am very curious about https://svelte-native.technology/ so hopefully I will find time to learn more about that some time in the future.

**Comment by BobWs** [comment]
> I'm not sure to be honest. Maybe @BobWs lost interest?
> 
> I haven't created a new issue, since I don't have time to look at it atm. I am very curious about https://svelte-native.technology/ so hopefully I will find time to learn more about that some time in the future.

Correct lost interest, but please feel free to open a new or reopen this issue if you are still interested.
