### ISSUE TITLE
Missing last unicode character in highlighted URL

### ISSUE THREAD

**Issue by Svetlana-T** [convos-chat/convos#563]
**Describe the bug**
```
<gry> https://ru.wikipedia.org/wiki/Участница:Gryllida/Черновик  last symbol shows as separate outside of the URL? do you reproduce the bug?
<gry> i mean the 'к'
<@batman> gry: Yes, I do. Can you open an issue? I have to start working now, and I'm going on a trip this weekend, so it would be nice to have an issue so I don't forget fixing it next week
<@batman> Or... Give me a sec...
<@batman> Yeah, that's not straight forward in javascript unfortunately
<@batman> The issue is the \W in https://github.com/Nordaaker/convos/blob/master/assets/js/md.js#L155
```

**To Reproduce**
1. write https://ru.wikipedia.org/wiki/Участница:Gryllida/Черновик in a chat
2. Click on the link
4. See error page not found, because the link clipped last symbol unnecessarily

**Expected behavior**
open full URL including the last к symbol in it

**Screenshots**

**Environment:**
 - OS: [e.g. iOS, Ubuntu, Windows 10, ...]
 - Browser [e.g. chrome, firefox, ...]
 - Version [e.g. 2.0]
 - IRC server software, name and/or version.

**Additional context**

**Comment by jhthorsen** [comment]
I created a failing test in https://github.com/Nordaaker/convos/commit/1d5d58a7c4be258d57f735e5947867e1a993f62b, but unfortunately matching unicode characters is not super easy to do in JavaScript.
