### ISSUE TITLE
Nick autocomplete does not work in Chrome on Android

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [convos-chat/convos#571]
**Describe the bug**
Using `@` followed by the beginning letters of a nick doesn't trigger the autocomplete feature on mobile

**To Reproduce**
1. Go to your convos instance URL on your smartphone
2. Go to any channel
3. Type `@` followed by some letters of the nick you want to highlight

**Expected behavior**
The same behavior from desktop web should happen and trigger autocomplete

**Screenshots**
See below.

**Environment:**
 - OS: Android
 - Browser Chrome
 - Version 88.0.4324.152
![22q0cYNWNdqxvLdm](https://user-images.githubusercontent.com/25697531/108235570-38d40300-7146-11eb-8d48-08dba6019753.jpg)

**Comment by jhthorsen** [comment]
I cannot reproduce this.

<img width="396" alt="Screen Shot 2021-07-17 at 20 31 58" src="https://user-images.githubusercontent.com/45729/126035495-c326db97-193e-4950-860c-0f46c972f588.png">

**Comment by PeGaSuS-Coder** [comment]
Using a Xiaomi Poco M3 phone (Android 10) and Chrome 91.0.4472.164 I still have the issue.
I've uploaded [this video](https://streamable.com/gs37r3) where you can see that it doesn't work with me.

Cheers

**Comment by jhthorsen** [comment]
I'm using browserstack and I've tested on four different Android phones now and I cannot reproduce it. You might still have an issue, but unfortunately I don't have a way to fix it.

<img width="781" alt="Screen Shot 2021-07-17 at 21 10 32" src="https://user-images.githubusercontent.com/45729/126036427-7f4efcce-5e16-4db6-b879-3caa7a206587.png">

**Comment by PeGaSuS-Coder** [comment]
Just for the sake of laugh: [this](https://streamable.com/64iegq) works.
My phone is pretty much with the default settings except for allowing installation apps that have been sideloaded.
