### ISSUE TITLE
Are convos.by and Nordaaker imposters?

### ISSUE THREAD

**Issue by lehnins** [convos-chat/convos#574]
Are these sites offical?

https://convos.by/

https://github.com/Nordaaker/

**Comment by jhthorsen** [comment]
* convos.by is an imposter site: https://twitter.com/convosby/status/1362667227804131331?s=20
* Nordaaker is the original company behind Convos, but we moved Convos to convos-chat org during the 6.00 release

No idea how to fix the convos.by issue 😞

**Comment by jhthorsen** [comment]
I'm closing this as wontfix, since it's out of our control.
