### ISSUE TITLE
Improvements for Source IP setting

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [convos-chat/convos#575]
Now that Convos allow us to set a source IP, there are a few improvements that could be made.

Below there's a small set of ideas.
- [ ] Have an option to set a `global source IP` on a per user basis, that would be applied on all the connections of that user.
- [ ] If the `global source IP` gets implemented, changing the global source IP would make each user reconnect on all the connected networks.
- [ ] When the source IP is changed for an already established connection, the users should be reconnected to the network in order to use the new IP.
- [ ] An option to allow only admins to change users IP like `Allow users to change their source IP?`.
- [ ] An option to allow admins to change other users IP on a network/global basis from the `Users` menu on the Admin panel.
- [ ] An option to toggle WEBIRC on/off on the settings and specify the IP and password to be used, which would be only editable by admins and hidden from everyone else.

**Comment by jhthorsen** [comment]
I don't see this getting implemented any time soon. I'll accept a PR though.

Putting this in the fridge for now.
