### ISSUE TITLE
Convos locks up after connecting to specific IRC Server

### ISSUE THREAD

**Issue by jsuelwald** [convos-chat/convos#577]
**Describe the bug**
The convos server kindof freezes after a while after being connected to specific irc-servers
I think the convos server dies when trying to retrieve a Channel list on that server.

Reason for this belive is this server Response: "Usage of /list for listing all channels is deprecated. Please use "/squery alis help" instead."

**To Reproduce**
1. Add a connection to irc.uni-erlangen.de
2. Try to join a channel

**Expected behavior**
Should be able to get a channel list and join a channel.

**Screenshots**
Log:

> [2021-02-23 08:02:55.81724] [8645] [info] Listening at "http://0.0.0.0:8080"
Web application available at http://0.0.0.0:8080
Argument "&" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "i" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "nuby" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "dig" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Use of uninitialized value in substitution (s///) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 402.
Mojo::Reactor::EV: I/O watcher failed: Can't use an undefined value as an ARRAY reference at /root/convos/lib/Convos/Core/Connection/Irc.pm line 205.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Mojo::Reactor::EV: I/O watcher failed: Can't use an undefined value as an ARRAY reference at /root/convos/lib/Convos/Core/Connection/Irc.pm line 205.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Use of uninitialized value in pattern match (m//) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 872.
Argument "NOTICE" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "NOTICE" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "NOTICE" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.
Argument "NOTICE" isn't numeric in addition (+) at /root/convos/lib/Convos/Core/Connection/Irc.pm line 398.

**Environment:**
 - OS: Ubuntu Server 20.04 LTS
 - Browser Vivaldi (Current)
 - Version: Latest stable as of 2021-02-23
 - IRC server irc.uni-erlangen.de - Version;: 2.11.2p3. Uni-Erlangen.DE 276E aCEFHJKlmMpQRsTuZ6

**Comment by jhthorsen** [comment]
When you say "Try to join a channel" does that mean that you go to "Add conversation" in the sidebar, or running "/join #channelname" ?

**Comment by jsuelwald** [comment]
Using /JOIN works.
Using Add Conversation: Convos dies.

IRC server irc.uni-erlangen.de - Version;: 2.11.2p3. Uni-Erlangen.DE 276E aCEFHJKlmMpQRsTuZ6

**Comment by jhthorsen** [comment]
I'm thinking this should be fixed in some/all of these places:

* https://github.com/convos-chat/convos/blob/37a0ade9dc5c2fd471d7c03a7008a1b5d5afd4ee/lib/Convos/Core/Connection/Irc.pm#L914
* https://github.com/convos-chat/convos/blob/37a0ade9dc5c2fd471d7c03a7008a1b5d5afd4ee/lib/Convos/Core/Connection/Irc.pm#L392-L405

But unfortunately I have no idea how to fix it. Running convos with `CONVOS_LOG_LEVEL=trace` would give som valuable output.

Going to close this issue for now, since I think it has gone stale.
