### ISSUE TITLE
Websocket doesn't work in HTTPS

### ISSUE THREAD

**Issue by Industrial** [convos-chat/convos#581]
**Describe the bug**
I deployed Convos to HTTPS and got the error `[Socket:error] 2021-03-21T13:14:05.738Z The operation is insecure. DOMException: The operation is insecure.`

**To Reproduce**
Deploy via HTTPS

**Expected behavior**
Websocket uses `wss://` instead of `ws://`.

**Screenshots**

**Environment:**
 - Cloud: AWS
 - OS: linux
 - Browser firefox
 - Version `:stable`

**Comment by jberger** [comment]
If you're behind a proxy you'll need to set it up according to https://convos.chat/doc/reverse-proxy . If that doesn't fix the issue please reopen with more detail.

**Comment by jhthorsen** [comment]
To answer another question from IRC: Some things can be configured via $ENV. See https://convos.chat/doc/config for more information.

**Comment by Industrial** [comment]
@jberger, @jhthorsen Thanks! I should have read the documentation more thoroughly..
