### ISSUE TITLE
Add logfile for login attempts to enable fail2ban filtering.

### ISSUE THREAD

**Issue by someusernamethatisnotnotavailable** [convos-chat/convos#582]
The current version does not create logfiles, so preventing brute force attacks requires some other measures than fail2ban. It would therefore be comfortable to have a log file, e.g. at /var/log/convos/convos-status.log. (the subdirectory is for granting user rights) The logfile should contain a timestamp, the IP of the client trying to log in and a recognizable error code, e.g. 
"[Timestamp], [IP], Login failed: Invalid email or password." The starting time/date of the daemon could also be logged.

I made a miserable workaround for my installation, it works partially and is better than nothing:
In the file convos-stable/lib/Convos/Plugin/Auth.pm I replaced the code:

    sub _login_p {
        my ($c, $args) = @_;
        my $user = $c->app->core->get_user($args);
        return Mojo::Promise->resolve($user) if $user and $user->validate_password($args->{password});
        return Mojo::Promise->reject('Invalid email or password.');
    }

with

    sub _login_p {
        my ($c, $args) = @_;
        my $user = $c->app->core->get_user($args);
        return Mojo::Promise->resolve($user) if $user and $user->validate_password($args->{password});
        open(my $logfile, '>>', '/var/log/convos/convos-status.log') or die $!;
        print $logfile scalar localtime() . ", Login failed: Invalid email or password.\n";
        close($logfile);
        return Mojo::Promise->reject('Invalid email or password.');
    }

The directory /var/log/convos was created manually for my user "convos". This extra code creates entries for every failed login. I am lacking the programming abilities to find out how to add the IP of the client though. Once a proper logfile is given by convos an appropriate fail2ban filter can easily be set up.

Thank you in advance.

**Comment by jhthorsen** [comment]
You can use `$c->tx->remote_address` to get the remote address.

https://docs.mojolicious.org/Mojo/Transaction#remote_address

**Comment by someusernamethatisnotnotavailable** [comment]
Thank you @jhthorsen, I tried tried your suggestion and it works like a charm. :-)

For completeness, here are all changes I made:

In the file `convos-stable/lib/Convos/Plugin/Auth.pm` I replaced the code:

    sub _login_p {
        my ($c, $args) = @_;
        my $user = $c->app->core->get_user($args);
        return Mojo::Promise->resolve($user) if $user and $user->validate_password($args->{password});
        return Mojo::Promise->reject('Invalid email or password.');
    }

with

    sub _login_p {
        my ($c, $args) = @_;
        my $user = $c->app->core->get_user($args);
        return Mojo::Promise->resolve($user) if $user and $user->validate_password($args->{password});
        open(my $logfile, '>>', '/var/log/convos/convos-status.log') or die $!;
        print $logfile scalar localtime() . ", IP: " . $c->tx->remote_address  . ", Login failed: Invalid email or password.\n";
        close($logfile);
        return Mojo::Promise->reject('Invalid email or password.');
    }

For logging the start of the daemon I added in `/home/convos/convos-stable/lib/Convos/Core.pm` at the beginning:

    open(my $logfile, '>>', '/var/log/convos/convos-status.log') or die $!;
    print $logfile scalar localtime() . ", Convos daemon started.\n";
    close($logfile);

(Not sure if this is the proper place but it works and gives a log entry when the daemon starts.)

To allow the logfile to be written from a non-root user I added a folder `/convos` in `/var/log` (i.e. `/var/log/convos`) and gave owership to the user that runs the daemon.

To make it work with fail2ban, I added the following lines in `/etc/fail2ban/jail.local`:

    #
    # Convos server
    #
    
    [convos]
    
    enabled  = true
    port     = [whateverportyouuse]
    protocol = tcp
    filter   = convos
    logpath  = /var/log/convos/convos-status.log
    maxretry = 5

The filter code was added to a new file `/etc/fail2ban/filter.d/convos.local`:

    #
    # Fail2Ban filter for Convos rejections
    #
    
    [Definition]
    
    # Example message:
    # Wed Mar 31 18:24:02 2021, IP: 117.207.115.143, Login failed: Invalid email or password.
    
    failregex = <HOST>, Login failed: Invalid email or password.
    
    ignoreregex =

After a restart of fail2ban I am able to see unsuccessful login attempts (`sudo fail2ban-client status convos`) as intended, and the source IP gets banned when `maxretry` is reached.

**Comment by jhthorsen** [comment]
The code in master will log lines like this now:

```
[2021-04-05 11:31:36.91606] [57297] [warn] login_p({"email":"superman@example.com","remote_address":"127.0.0.1"}) FAIL Invalid password.
[2021-04-05 11:31:36.93518] [57297] [info] login_p({"email":"superman@example.com","remote_address":"127.0.0.1"}) SUCCESS Valid email and password..
```
