### ISSUE TITLE
 SSL connect attempt failed error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by grandfoobah** [convos-chat/convos#583]
Hi,

I am running a oragono container and convos container behind traefik in docker.

Traefik serves the convos webapp at https://chat.example.com

oragono is expose: 6667 , only available internally with the hostname oragono:6667

When a new user registers, it tries to connect, and errs with 

` SSL connect attempt failed error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

While if they delete the network, and then add it again, using "add connection" => "create" (leaving settings defaults) it will then finally be able to connect.

The setting in use is irc://oragono:6667 with force default connection ticked.

I can't figure out why it's trying to connect over ssl by default on a 6667 irc server. Thanks.

**Comment by jhthorsen** [comment]
It tries to detect if the server support SSL or not. If you want to force no TLS, then you have to change the URL to:

irc://oragono:6667?tls=0

**Comment by grandfoobah** [comment]
When I add ?tls=0 I fail to get the real IP of the user

**Comment by grandfoobah** [comment]
When I remove ?tls=0 the issue of this thread remains, when I add ?tls=0 the /whois information is wrong

  guest (~u@localhost, https://convos.chat)has been idle for 14s, and is not in any channels.

**Comment by grandfoobah** [comment]
I do find that when I remove the connection, and manually re-add the connection, unticking the ssl box, it does connect as desired and show the correct IP.

The issue seems to be around the connection options being used by a newly registered user, with force default connection ticked.

**Comment by jhthorsen** [comment]
The "Default connection URL" in "Settings" was hard to understand, so I made a new connection editor instead. This has been merged #584.
