### ISSUE TITLE
Add support for "Check for updates" - Privacy issue?

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#585]
I would like to add a "Check for updates" setting to the "Settings" section of Convos. This setting should make Convos check a resource to see if a new Convos version is available or not. This check can be disabled, in case a user does not want the Convos installation to "phone home". It will also automatically run on an interval, like once a day or maybe once a week.

The reason behind this setting is...

1. I think many are running old versions of Convos, simply because there's no automatic updates.
2. I would like to get some metrics of how many Convos installations are out there, and which versions they are running.

The second reason might be something that some users will not be a fan of, so it needs to be easy to opt out.

I'm thinking Convos could fetch `https://convos.chat/api/version?running=5.30&appId=xyz`, where "running" is the version the calling Convos installation is running and appId could be generated by `Convos::Util::generate_secret()`.

**Comment by serhack** [comment]
Wouldn't be better to have a check with Github Releases API? We should try to avoid any "point of failure" (such as `convos.chat` domain...).

**Comment by jhthorsen** [comment]
@serhack: That is not possible, since we don't have any releases on GitHub.

**Comment by serhack** [comment]
@jhthorsen: the issue was not about Github releases, but about the "Check for update" feature. IHMO I do not think that feature is essential to Convos.

**Comment by serhack** [comment]
Oh, didn't notice the latest commits. Great work 👏🏻
