### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by grug0r** [convos-chat/convos#586]
**Describe the bug**
Internal Server Error (500) **and** [2021-04-10 01:13:41.02107] [35347] [error] [tWPCxv06Gz9W] Could not render a response at /home/jameso/convos/local/lib/perl5/Mojo/Promise.pm line 235.

**To Reproduce**
1. Click on Log out

**Environment:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser Chrome

**Comment by jhthorsen** [comment]
That was an interesting bug. Not sure why it's not triggered by the unit tests...

Either way, it will be fixed in the next release.

Thanks for reporting!
