### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by ElvishJerricco** [convos-chat/convos#589]
There should be an optional sound when you get a notification.

**Comment by jhthorsen** [comment]
One of the problems here is to find a notification sound file with the correct license that also sounds good. Maybe someone can find one for me?

**Comment by serhack** [comment]
https://freesound.org/search/?q=notification&f=license%3A%22Creative+Commons+0%22&s=score+desc&advanced=0&g=1

**Comment by acagastya** [comment]
Using `play_pattern_timed chord(:E3, :m13), [0.1, 0.1]` in sonic pi, I made: 
[notification.wav.tar.gz](https://github.com/convos-chat/convos/files/6565794/notification.wav.tar.gz), if one needs a free tune for notification.

My suggestion for this is -- to allow users to enable or disable sound, and allow them to have custom notification tune as well.

**Comment by mpmc** [comment]
> 
> 
> Using `play_pattern_timed chord(:E3, :m13), [0.1, 0.1]` in sonic pi, I made:
> [notification.wav.tar.gz](https://github.com/convos-chat/convos/files/6565794/notification.wav.tar.gz), if one needs a free tune for notification.
> 
> My suggestion for this is -- to allow users to enable or disable sound, and allow them to have custom notification tune as well.

This is great. I think this should be the default (if licensing allows). Once this issue is fixed I'll be switching over to convos from znc/hexchat :)

**Comment by jhthorsen** [comment]
@serhack: That is a long list.

@acagastya: I think it's a bit long.

**Comment by jhthorsen** [comment]
This is part of the 6.48 release. Please let me know what you think.

I don't want to change the notification sound too often/many times, but it's not impossible to change it. Especially since there wasn't a vote the first time.
