### ISSUE TITLE
Option to mention on click instead of opening PM

### ISSUE THREAD

**Issue by Synthetica9** [convos-chat/convos#591]
**Is your feature request related to a problem? Please describe.**
I came from irccloud, and a future I used a lot was "click to mention". When you click a name there, it inserts `<username>:` in the chat field.

**Describe the solution you'd like**
I'd also like this behaviour (optionally) in Convos. I think the ideal solution would be to have a normal click insert a mention, and shift-click open a private chat, but with an option to reverse this to preserve current behaviour.

**Describe alternatives you've considered**
I guess I could just keep selecting the username and copy-pasting it, but that's a lot more actions...

**Comment by marcusramberg** [comment]
are you aware of the @<nick> autocomplete? (As another alternative)

**Comment by Synthetica9** [comment]
No, I wasn't! I guess that's also a good alternative. However, it might still be nice to have both

(and thank you for the incredibly quick response!)

**Comment by jhthorsen** [comment]
We actually used to have this feature, but we changed it to opening a chat during a Convos hackathon iirc, after requests from multiple users.

There is a problem with the proposition and that is difference between touch screen and keyboards: I don’t know how this would be done on mobile, which is the platform where I miss this feature the most…

I also wonder if this is in conflict with #566.

**Comment by jhthorsen** [comment]
This is now part of the menu in #566 - https://github.com/convos-chat/convos/issues/566#issuecomment-850757459
