### ISSUE TITLE
Improper colour stripping regex leads to change of content in messages.

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#600]
Consider this following message which contains the colour codes.
`[[\x0307Wikinews:Sandbox\x03]]  \x0302https://en.wikinews.org/w/index.php?diff=4621760&oldid=4621759\x03 \x0305*\x03 \x0303103.48.104.126\x03 \x0305*\x03 (+2) \x0310more test\x03`

The [current regex](https://github.com/convos-chat/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L365-L367) is stripping "103" from "103.48.104.126".

A patch which can prevent logs from having incomplete messages till we decide if we want to support colours, or if we want the users to toggle colour for the chats.
[0001-Fix-colour-stripping-regex.patch.txt](https://github.com/convos-chat/convos/files/6568197/0001-Fix-colour-stripping-regex.patch.txt)

The commit message in the patch explains why `s/\x03(0[0-9]|1[0-5])(,(0[0-9]|1[0-5]))?//g` will fix the problem.

---

From CONVOS_DEBUG
```
[irc-libera] Save success. (/Users/acagastya/.local/share/convos/foo@bar.com/irc-libera/connection.json)
[foo@bar.com/irc-libera] [36099/305] <<< PING tungsten.libera.chat\x0d
[foo@bar.com/irc-libera] [36099/305] >>> :tungsten.libera.chat PONG tungsten.libera.chat :tungsten.libera.chat
[foo@bar.com/irc-libera] [36099/305] ->_irc_event_pong(...)
[foo@bar.com/irc-libera] [36099/308] >>> :enwnrc!~enwnrc@user/enwnrc PRIVMSG #en.wn :[[\x0307Wikinews:Sandbox\x03]]  \x0302https://en.wikinews.org/w/index.php?diff=4621760&oldid=4621759\x03 \x0305*\x03 \x0303103.48.104.126\x03 \x0305*\x03 (+2) \x0310more test\x03
[foo@bar.com/irc-libera] [36099/308] ->_irc_event_privmsg(...)
```

**Comment by jhthorsen** [comment]
I want to fix this by removing the regex complete from Irc.pm and rather strip/render the escape codes in frontend.

https://github.com/convos-chat/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L365-L367 

I still don't know how to render colors (because I believe it's in conflict with different themes), but at least we can render bold/italic/underline.

* https://www.mirc.com/colors.html
* http://www.ircbeginner.com/ircinfo/colors.html

**Comment by acagastya** [comment]
The current solution of dropping the replacement, but providing no means of displaying the colour is messing up the messages, the pings don't create a notification, and the urls are non-clickable.  Trimming them was necessary until a fix for showing the colours was available.  Could you please revert those changes?
