### ISSUE TITLE
Backticks containing a single character are not highlighted

### ISSUE THREAD

**Issue by OnlineCop** [convos-chat/convos#602]
**Problem:**
Backticks surrounding a single character should highlight as code blocks.

When two backticks surround a single character, that character should be surrounded within \<code>\</code> blocks. Currently, only the ampersand appears to be:

https://imgur.com/a/y1eQV62

When two backticks surround two or more characters, it appears to surround them with \<code>\</code> blocks as expected.

**Argument:**
I help and display regular expressions in IRC (#java, #regex) regularly. Often, emphasis with backticks is made to convey that some text is part of a regex pattern, and not the text/data to be evaluated. It's not uncommon for a single character to be written with backticks: "The \`*\` quantifier is used to... the \`+\` quantifier is used to... the \`?\` quantifier is used to... the \`?\` appended to a quantifier changes its behavior to... the \`+\` appended to a quantifier changes its behavior to..."

When sentences contain a mixture of single-characters and multi-characters surrounded by backticks, the current logic can often move the \<code>\</code> highlight to the wrong section (see first image in earlier screenshot).

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v6.24

**Additional question:**
Would tests for backticks go into the [I18N.js](https://github.com/convos-chat/convos/blob/master/__tests__/store/I18N.js) file, or another location?

**Comment by jhthorsen** [comment]
Yes, the tests should go into I18N.js and the fix should be in https://github.com/convos-chat/convos/blob/master/assets/store/I18N.js#L118-L121

I welcome a PR, and I'm very grateful that you explained *why* this change is needed 👍

**Comment by jhthorsen** [comment]
It would be awesome if you could follow https://convos.chat/doc/develop to set up the dev environment and then submit a PR.
