### ISSUE TITLE
Typing Indian Rupee produces Russian Rubel in the message box

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#603]
**Describe the bug**
When typing `₹`, `₽` shows up in the message box on various browsers/OS.

**To Reproduce**
1. Type `₹` in message box.

**Expected behavior**
`₹` should be visible instead of Russian Rubel

**Screenshots**

![](https://convos.hanabi.in/file/1/0pg4v0CdRZuvV58X.png)
![](https://i.imgur.com/xN9GRLK.jpeg)

**Environment:**
 - Firefox (34) on iOS (12.4.1)
 - Firefox (89) on Ubuntu (18.04)
 - Firefox Android.

**Comment by jhthorsen** [comment]
I can't seem to reproduce this:

<img width="136" alt="Screen Shot 2021-07-17 at 20 04 10" src="https://user-images.githubusercontent.com/45729/126034919-908164e1-103e-4e33-892f-bc03f6447566.png">

**Comment by acagastya** [comment]
@jhthorsen Which browser/OS are you testing it on?

**Comment by jhthorsen** [comment]
Latest Firefox on macOS.

**Comment by acagastya** [comment]
@jhthorsen As mentioned in the problem, could you please try reproducing the bug in one of these environments?
+ Firefox (34) on iOS (12.4.1)
+ Firefox (89) on Ubuntu (18.04)
+ Firefox Android

This problem seems to be happening on iOS even today.

**Comment by jhthorsen** [comment]
I don't mind changing the font from "PT Sans", but I'm not sure what to change it to. Can you see if the following diff fixes anything?

```
diff --git a/assets/sass/base/_root.scss b/assets/sass/base/_root.scss
index 9a979e10a..cb3354f6c 100644
--- a/assets/sass/base/_root.scss
+++ b/assets/sass/base/_root.scss
@@ -1,7 +1,18 @@
 :root {
   --body-bg: #f8f9f8;
   --cms-bg: var(--body-bg);
-  --font-family: "PT Sans", Helvetica, Arial, sans-serif;
+  --font-family: system-ui,
+    /* macOS 10.11-10.12 */ -apple-system,
+    /* Windows 6+ */ Segoe UI,
+    /* Android 4+ */ Roboto,
+    /* Ubuntu 10.10+ */ Ubuntu,
+    /* Gnome 3+ */ Cantarell,
+    /* KDE Plasma 5+ */ Noto Sans,
+    /* fallback */ sans-serif,
+    /* macOS emoji */ "Apple Color Emoji",
+    /* Windows emoji */ "Segoe UI Emoji",
+    /* Windows emoji */ "Segoe UI Symbol",
+    /* Linux emoji */ "Noto Color Emoji";
```

**Comment by jhthorsen** [comment]
I consider this issue abandoned.
