### ISSUE TITLE
KVIrc Legacy Avatar Protocol

### ISSUE THREAD

**Issue by SoniEx2** [convos-chat/convos#604]
**Is your feature request related to a problem? Please describe.**

Currently avatars aren't well supported and the options for setting them aren't very good.

**Describe the solution you'd like**

KVIrc hides an U+0003 '4' U+000F, U+0003 '5' U+000F, U+0003 '6' U+000F or U+0003 '7' U+000F sequence (a hidden color code, which doesn't show up on IRC clients. it's a bit field, but the lower bits aren't important for or even related to avatars and as such shouldn't be part of this feature request, just send them as 0 i.e. only use '4'.) at the start of realname to signal to other clients that CTCP AVATAR is supported.

CTCP AVATAR is either a request (`AVATAR`) or a response (`AVATAR https://example.org/...`) with the usual CTCP request/response rules (PRIVMSG vs NOTICE etc).

It would be a good idea to delay avatar requests until the user's avatar would be visible (either on the userlist or the chat), especially for larger channels. A low-priority avatar request queue could also be used, but since avatar requests do interact with flood limiting, this is not the best solution and we'd still rather go with the delayed/visibility-based requests.

**Describe alternatives you've considered**

The main alternative is to not bother supporting this. It's not exactly an alternative that can be feature requested tho.

**Additional context**

**Comment by marcusramberg** [comment]
http://www.kvirc.net/doc/doc_ctcp_avatar.html guess this is the "spec". Are there other competing standards out there?

**Comment by SoniEx2** [comment]
Uh we guess there's irccloud's thing and gravatar-in-realname. The former of which can't be sent by convos and the latter is often seen as too privacy-invasive *and* takes over the realname, preventing its normal use.

**Comment by marcusramberg** [comment]
Why can't we use the irccloud version? Seems to be built around a ircv3 standard? https://blog.irccloud.com/avatars/

**Comment by SoniEx2** [comment]
Maybe one day. Generally IRC clients that support avatars will support at least gravatar and irccloud (the userid-based ones). There's nothing really preventing an IRC client from supporting legacy protocols like KVIrc's and then also adding support for IRCv3/irccloud (private) if that ever becomes a thing.

KVIrc's does have a benefit that the irccloud one doesn't: The client is in full control over what requests it fulfills. This provides better privacy, especially when combined with ACLs.

**Comment by DarthGandalf** [comment]
> only '4' should be sent, the others should be considered deprecated

KVIrc dev here. Those numbers are NOT deprecated, even if Soni wishes them to be.

> CTCP AVATAR is either a request (AVATAR) or a response (AVATAR https://example.org/...)

Or the response could be served via DCC instead of URL. Soni, if you're proposing using an existing protocol, try to at least investigate (or ask!) how it works. Otherwise you'll end up with an incompatible implementation.

**Comment by SoniEx2** [comment]
It's true, it does have a DCC option. But as it's 2021 we think it's way past time to let DCC die. So supporting it HTTPS-only sounds good.

**Comment by DarthGandalf** [comment]
> But as it's 2021 we think it's way past time to let DCC die

Sure. I'm just saying that what you're proposing here will already be incompatible with what KVIrc does. Which defeats the point of implementing the same protocol.

TBH, I really suggest going IRCv3 route instead.

**Comment by SoniEx2** [comment]
From personal experience a lot of avatars *are* HTTPS! Well... many are HTTP, but, still. DCC avatars are definitely far from the norm.

**Comment by jhthorsen** [comment]
I'm going to put this issue in the Fridge for now. Feel free to open a PR if you want it sooner.
