### ISSUE TITLE
Search for "+" doesn't show all the channels with unread messages

### ISSUE THREAD

**Issue by castaway** [convos-chat/convos#607]
**Describe the bug**
I have 3 channels with unread messages, 2 with "60+" indicators, and one with "52". When I type "+" into the search box, only the "52" messages one is listed, the other two are not - I assume they all should.

**To Reproduce**
1. Lurk long enough to get channels with "60+" unread messages (I am assuming these are the issue)
2. type "+" into search box

**Expected behavior**
All three channels with unread messages to be listed

**Screenshots**

**Environment:**
- Linux, Vivaldi 4.0, libera.chat

**Additional context**

**Comment by serhack** [comment]
Confirmed on Debian, Firefox, libera.chat .

**Comment by jhthorsen** [comment]
This is not a bug, it's by design: We consider 60+ channels to be channels you don't care much about, so that's why it's not hidden. You can however filter all those channels by just searching for "60" or "60+".

**Comment by castaway** [comment]
Ah.. I'd say not entirely intuitive (or documented) design, personally ;)

**Comment by jhthorsen** [comment]
I've changed this now to also search for "60+".
