### ISSUE TITLE
Previews for content containing double quotes displays "&quot;"

### ISSUE THREAD

**Issue by castaway** [convos-chat/convos#608]
**Describe the bug**
convos_bot displays previews of links with text - if the text contains double quotes, it seems to (sometimes?) display &quot; instead

**To Reproduce**
1. Create github issue for convos containing double quotes
2. Watch convos_bot report it..

**Expected behavior**
Double quotes should be output as double quotes, not entities

**Screenshots**
![image](https://user-images.githubusercontent.com/109990/122905269-fbc48b00-d348-11eb-8249-465f58f3ffdd.png)

**Environment:**
- Linux (Gentoo), Perl 5.32, Vivaldi 4.0 

**Additional context**

**Comment by jhthorsen** [comment]
This was actually fixed in https://github.com/convos-chat/linkembedder/commit/9ae1d40d046af71dd1309373c55750663c3b73d6
