### ISSUE TITLE
Settings option to only display channels/chats with activity

### ISSUE THREAD

**Issue by castaway** [convos-chat/convos#609]
**Is your feature request related to a problem? Please describe.**
I'm looking to switch over from irssi, and thus for features that will support my 100+ channel/window habit. 

**Describe the solution you'd like**
A setting added in Account that would allow (per user) a choice of completely hiding channels from the side bar list, unless they have recent activity.

**Describe alternatives you've considered**
I'm sure I'll have more ideas.. 

**Additional context**

**Comment by jhthorsen** [comment]
Would #520 be an alternative?

**Comment by castaway** [comment]
Maybe, I did read that one .. why not both? ;)

**Comment by jhthorsen** [comment]
Same reason as https://www.omgubuntu.co.uk/2021/07/why-gnome-does-what-gnome-does-by-tobias-bernard

I think #520 is a better solution, so I'm going to close this. I'll consider a PR though, but maybe you want to discuss how you think this will actually look/behave on irc.libera.chat first.

**Comment by jhthorsen** [comment]
I just found a "hack" to do this: The search input field will now "remember" "+" (instead of clearing it on blur), so if you enter "+" it will only show channels with unread messages.

**Comment by castaway** [comment]
awesome!
