### ISSUE TITLE
Warn users before deleting a connection

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#610]
**Is your feature request related to a problem? Please describe.**
I learned the hard way, when deleting a connection, ALL logs are deleted.  A discussion with @jhthorsen on IRC suggests this is an expected behaviour.

**Describe the solution you'd like**
I would recommend asking for a confirmation when one clicks "delete".  Additionally, a warning that all logs of that connection will be deleted in big bold font would be really helpful.

**Describe alternatives you've considered**
None.

**Additional context**
I think this suffices.

**Comment by jhthorsen** [comment]
I just want to say that even thought it is indeed *expected*, it's far from the wanted behavior.

I support this change request 100% 👍 

I think however that I might show an input field where you have to enter the name of the connection to verify. Very much the same as when you want to delete a git repo on github.

**Comment by jhthorsen** [comment]
This will be fixed in the upcoming release.

<img width="615" alt="Screen Shot 2021-07-17 at 16 57 30" src="https://user-images.githubusercontent.com/45729/126030357-5f3855b4-d09c-4a9c-94ef-9e318f231f69.png">
