### ISSUE TITLE
Ability to toggle collapse of chats in any given connection

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#611]
**Is your feature request related to a problem? Please describe.**
Consider the following image.  
<img width="302" alt="Screenshot 2021-07-04 at 08 40 06" src="https://user-images.githubusercontent.com/5466083/124410193-7c1bc080-dd39-11eb-8c25-0df8530b6291.png">
I would not call it problem per se, but having many channels and chats in a connection could be too distracting.

**Describe the solution you'd like**
I would suggest having a ▶/▼ to toggle hide/show of the list (hidden by default) might be a good idea.  Maybe an aggregate message count number like this screenshot would be a good idea?  (First one is how it looks currently, second is the proposed solution.)
<img width="286" alt="Screenshot 2021-07-05 at 02 41 28" src="https://user-images.githubusercontent.com/5466083/124410948-03b5ff00-dd3b-11eb-8fa6-fa53b8b76b93.png">
<img width="299" alt="Screenshot 2021-07-05 at 02 44 25" src="https://user-images.githubusercontent.com/5466083/124410964-0dd7fd80-dd3b-11eb-87d6-1b6cf9c1f17b.png">

**Describe alternatives you've considered**
None.

**Additional context**
I think that should suffice.

**Comment by jhthorsen** [comment]
I don't think this is a good idea. I can't imagine a situation where I want to "constantly" toggle the whole list just to see what hides under that unread count.

I think there's other ways to do this better:
* Toggle hide/show favorite channels
* #520
* #609

I'll leave the issue open for a while, but will probably close it unless some other compelling argument is made. It's not that I don't see the problem, it's just that I don't think your suggested solution is optimal.

**Comment by jhthorsen** [comment]
I think #609 would be a better solution, but I'm going to close this since I also closed #609.
