### ISSUE TITLE
Apache Reverse Proxy: "Loading user data failed: Could not connect"

### ISSUE THREAD

**Issue by DarylGraves** [convos-chat/convos#613]
**Describe the bug**
I can't get Convos to work through an Apache2 reverse proxy when using the config suggested on the Convos website. It works fine if I access it via the the server name/ip and port directly.

I get the error "Loading user data failed: Could not connect" (screenshot below)

**To Reproduce**
- Download and install Convos, 
- Download Apache2, 
- Remove the content in **/etc/apache2/sites-avaialble/000-default.config** and copy the below instead

_Note that this is a copy-paste of the code listed [here](https://convos.chat/doc/reverse-proxy) with the ports changed and two lines commented out because Apache refuses to load with them. I don't think it's user error because I'm following the guide as close as possible..._

```
  ServerAdmin admin@your-domain.com
  ServerName your-domain.com


 #    Order allow,deny
 #   Allow from all


  # Enable Convos to construct correct URLs by passing on custom headers.
  ProxyRequests Off
  ProxyPreserveHost On
  RequestHeader set X-Request-Base "http://your-domain.com/"

  # https://httpd.apache.org/docs/current/mod/mod_remoteip.html
  RemoteIPHeader X-Forwarded-For

  # http://httpd.apache.org/docs/2.0/mod/core.html#limitrequestbody
  LimitRequestBody 0

  # Pass requests on to Convos
  ProxyPass /events ws://localhost:3000/events
  ProxyPass / http://localhost:3000/ keepalive=On
  ProxyPassReverse / http://localhost:3000/
```

- Run `sudo a2enmod remoteip` to install the module (this isn't mentioned in guide and ideally should be because this tripped me up for an hour or so!)
- Restart the Apache2 service (**sudo systemctl restart apache2.service**)
- Run `CONVOS_REVERSE_PROXY=1 ./script/convos daemon`
- In the browser go to your website.

**Expected behavior**
Application should work as it does without Apache

**Screenshots**
![image](https://user-images.githubusercontent.com/46203429/127788189-dca77a8b-fdb4-46dd-9b5b-d6cd07f566ed.png)

**Environment:**
Ubuntu 20.04.2 LTS

Thank you!

**Comment by jhthorsen** [comment]
How about this...

> Convos and the web server need to be configured properly and WebSockets need to be supported through the whole chain.

Are you sure your apache config loads the appropriate modules (or something) to support WebSockets? I haven't used Apache for a long time, so I don't know how this is done.

I would also check the developer console in your browser to see if there's any https/http issues.

I would appreciate if you could open up a PR for changes in https://github.com/convos-chat/www.convos.chat/blob/master/doc/reverse-proxy.md after you figure out the reason for this.

**Comment by castaway** [comment]
This is working fine for me on apache, current conf:
```
<VirtualHost *:443>
    #
    # DocumentRoot: The directory out of which you will serve your
    # documents. By default, all requests are taken from this directory, but
    # symbolic links and aliases may be used to point to other locations.
    #

    ServerName chat.jandj.me.uk

    # Enable Convos to construct correct URLs by passing on custom headers.
    ProxyRequests Off
    ProxyPreserveHost On
    RequestHeader set X-Request-Base "https://chat.jandj.me.uk/"

    # https://httpd.apache.org/docs/current/mod/mod_remoteip.html
    RemoteIPHeader X-Forwarded-For

    # http://httpd.apache.org/docs/2.0/mod/core.html#limitrequestbody
    LimitRequestBody 0
    ProxyPass /events ws://localhost:8800/events
    ProxyPass / http://localhost:8800/ keepalive=On
    ProxyPassReverse / http://localhost:8800/


Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/chat.jandj.me.uk/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/chat.jandj.me.uk/privkey.pem
</VirtualHost>
```

Running the application:
```
cd /usr/src/extern/convos; CONVOS_REVERSE_PROXY=1 script/convos daemon --listen http://*:8800 &
```

Re the Order allow,deny etc, in 2.4+ Apache that's done using "Require all granted" or similar - see https://httpd.apache.org/docs/2.4/upgrading.html

Looks pretty similar to me - does your terminal window say anything? (or the log files)

**Comment by castaway** [comment]
Although, did you actually set your server name / domain, or leave it at "your-domain" ?

**Comment by DarylGraves** [comment]
Thanks both!

Jess, you're spot on... I looked at the Browser Console first thing this morning and it was erroring because I left in "your-domain". My fault for trying to do something technical gone midnight!

I do plan to recreate the installation steps again and document it so I can submit a PR for the changes. The example setup aren't apparently valid and there are some modules which have to be enabled first before it will run.
