### ISSUE TITLE
HTML escape characters cause "undefined" to appear in URLs.

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#616]
**Describe the bug**
Consider the following URL: `https://commons.wikimedia.org/wiki/File:HK_WCD_WC_%E7%81%A3%E4%BB%94_Wan_Chai_%E8%BB%92%E5%B0%BC%E8%A9%A9%E9%81%93_Hennessy_Road_tram_body_ads_Tsingtao_Brewery_August_2021_SS2.jpg`

If you are using v6.24 -- the URL looks just fine.  See 
![Kfd7qJcrA4sT1Uxj](https://user-images.githubusercontent.com/5466083/131153506-614c3c71-48cf-4a5b-b3c5-6ca6f8f62983.png)

But if you are using v6.26 -- HTML escape characters in the URL are replaced with "undefined".  See 
![W1uT0C9lw4TdYTXB](https://user-images.githubusercontent.com/5466083/131154001-0a5fd9c1-76f3-40e0-b44a-426d12d65874.png)

The logs seem to be okay though.  @jberger tried this on docker and I tried with the normal set up -- the issue seems to be between v6.24 and v6.26.

**Comment by jhthorsen** [comment]
That was a bit surprising, but luckily not too hard to fix 👍 

Planning to make a new release later today, but I want to include some CSS fixes before releasing v6.27.
