### ISSUE TITLE
2 Channels if connect into channel with password

### ISSUE THREAD

**Issue by drfuture** [convos-chat/convos#621]
Hi,
i entered on my connection Profile (default connection + force connection) 

server: irc.xxxx.net:6667
Conversation Name: #chatroom CoolPassword

If i use this connection Profile, i enter the #chatroom with passwordprotection correctly but i have a second channel on my tree that shows the #chatroom and the Passwort exact as entered into "Conversation Name" with connection "Not Connected"

**Comment by jhthorsen** [comment]
I think the label is wrong: it should be “Conversation names”.
Why would you have a default channel that’s password protected?

**Comment by drfuture** [comment]
I have a channel for "internal use" of a fixed group of people.
i use convos as elegant webinterface to join from everywhere into this channel.

**Comment by drfuture** [comment]
Yes, ists a cooperation with a other community and there are public channels but this should not be accesable by this web instance.

**Comment by jhthorsen** [comment]
This should be fixed in 6.32.
