### ISSUE TITLE
Ability to disable File upload

### ISSUE THREAD

**Issue by drfuture** [convos-chat/convos#622]
it would be greate to have a option to hide / disable the feature vor Videochat and Fileupload if i wouldlike no external services.

**Comment by jhthorsen** [comment]
Video chat can be disabled in setting. Just clear out the value in the “Video service” field.

Why would you want to disable file uploads?

**Comment by drfuture** [comment]
Thx a lot for that quick answer.
Because i then dont like to give the space for this service to my users and simplify the ui to only show what is desired to use in my opinion.

**Comment by drfuture** [comment]
ok thx

**Comment by thenktor** [comment]
Hi!
I've just installed Convos on a test server in my LAN, that is not reachable from the internet. Therefore file upload also was the first thing I stumbled over: the uploaded files are not reachable by public IRC users.
I think it should be possible to disable them alltogether (or instead use an external service like https://transfer.adminforge.de/ ).
