### ISSUE TITLE
Inconsistent Docker build architecture

### ISSUE THREAD

**Issue by Flightkick** [convos-chat/convos#624]
**Describe the bug**
The available Docker images seem to have inconsistent architectures. This may be caused by https://github.com/convos-chat/convos/issues/464

Most explicit version tags have the amd64 architecture, except `v6.30` which is arm64.
Both `stable` and `arm64` are arm64

**To Reproduce**
1. Go to https://hub.docker.com/r/convos/convos/tags?page=1&ordering=last_updated
2. See the tags and their OS/Arch fields

**Expected behavior**
It is possible to share the same tag over multiple images with different architectures.
All users would be able to use the `stable` tag, regardless of architecture.
See Nginx tags for a comparison: https://hub.docker.com/_/nginx?tab=tags

**Screenshots**
![image](https://user-images.githubusercontent.com/8693699/137047235-382f636b-5dbc-4e5a-970d-205096215230.png)

**Additional context**
A mismatch between the host architecture and the container architecture could produce the following error:
```
exec user process caused: exec format error
```
_Encountered while running `stable` (which turned out to be arm64) on an amd64 host._

**Comment by jhthorsen** [comment]
I would very much like this to be fixed, but I don't want to wait 40+ minutes for the arm build to complete to get the amd64 docker image. See #618 for more details.

v6.30 was a bug, which got fixed (0f6d8ffdc48a664771ce1667820b9d9e69d7065a) by completely splitting up the docker tags: The amd64 builds will have the version number as tag, while the arm64 tag will simply be called "arm64".

**Comment by jhthorsen** [comment]
To fix the "exec format error" issue, then simply use v6.31 which is the latest.
