### ISSUE TITLE
As a user, I want to be able to sign in, but getting "ReferenceError: body is not defined" in Operation.js

### ISSUE THREAD

**Issue by nunolu** [convos-chat/convos#625]
I've installed the stable release of convos with docker. (version 6.34)
Container is starting fine without any issues.

When I go to http://ip:port I see the convos page with the Signup page
After entering email adress & password I receive following error:

Failed fetching operationId "registerUser": ReferenceError: body is not defined

Tried different browser (edge, firefox) / Also rebuilt the container but still the same issue

**Comment by nunolu** [comment]
No reverse proxy. I launched following docker and tried to access it directly with http://localhost:3133
https://imgur.com/1oNMeLO

docker run -d --name=convos \
-p 3133:3000 \
-v /mypath/convos:/data \
--restart always \
convos/convos:stable

**Comment by jhthorsen** [comment]
You can follow the progress at https://github.com/convos-chat/convos/actions/runs/1355095629

**Comment by jhthorsen** [comment]
Finally 6.36 is available. (Had some issues while trying to speed up the docker build)
