### ISSUE TITLE
Can't use “12345678” as the password (quotes are part of the password)

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#626]
**Describe the bug**
I can't use “12345678” as the password (quotes are part of the password).

**To Reproduce**
1. Go to `/settings/account`
2. Set password to `“12345678”`, or anything, which includes `“”`.
3. Save settings

You'd see "input must contain only octets" as the error message.

**Expected behavior**
The password should be okay to use, but isn't.

I am using v6.37.

**Comment by jhthorsen** [comment]
I can't reproduce this. I've tried writing a unit test and also live tested it with the quotes you provided, and I also tried to set the password to `foo bar baz 👍` (including the thumbs up), and it all works. I also can't find that error message anywhere.

**Comment by acagastya** [comment]
Does this video help, @jhthorsen?
https://user-images.githubusercontent.com/5466083/146712664-f5773d84-9c2e-40e8-8368-8970501a13fc.mp4
