### ISSUE TITLE
Nick wrongly gets taken

### ISSUE THREAD

**Issue by catdevnull** [convos-chat/convos#628]
**Describe the bug**
When running `/nick` with something invalid (for example, `Nulo!`), Convos changes the nick locally even though it doesn't actually get applied

**To Reproduce**
1. Go to a channel
2. Send a message `/nick Nulo!`

**Expected behavior**
Convos should throw an error when trying to apply it

**Screenshots**
![image](https://user-images.githubusercontent.com/86896666/141653402-ee22c6eb-7fbc-4743-8ae3-9b37628d0a22.png)

**Environment:**
 - OS: Linux
 - Browser: Firefox
 - Version: v6.37
 - IRC server software: Ergo 2.7.0

**Comment by jhthorsen** [comment]
Thanks for reporting in!

**Comment by catdevnull** [comment]
🥰 thanks.
