### ISSUE TITLE
Add a Clear Results button to the Search page

### ISSUE THREAD

**Issue by OnlineCop** [convos-chat/convos#631]
Could you add an 'x' in the corner of the Search page results to reset the page?

The first time the Search page is accessed, there are usually suggestions on how to filter by channel or nick. After a search is made, that is replaced by search results. There doesn't appear to be a way to clear the results and return to that default suggestion view. Hitting Enter with an empty search query does not appear to clear or change the results.

**Comment by jhthorsen** [comment]
While we are waiting for this to be implemented: A browser refresh (not just clicking in the sidebar) of the "Search" page will get the information text back.
