### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [convos-chat/convos#632]
Hey there!

I belong to an open source security research community, and a member (@dev696) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jhthorsen** [comment]
Thanks for the issue. You can send us an email using contact@convos.chat.

I’ll add the SECUITY.md file as soon as I have some extra time. Thanks for the tip 👍

https://convos.chat/doc#get-in-touch

**Comment by JamieSlome** [comment]
@jhthorsen - great! 👍 

Once the `SECURITY.md` has been created, we will sent further report details to your elected e-mail.

Otherwise, you can immediately view the private report here:

https://www.huntr.dev/bounties/77559ff3-0494-4186-b6e9-c4146bedc0df/

**Comment by stigtsp** [comment]
@DEV696 Thx for responsibly reporting the CSRF issue
