### ISSUE TITLE
Characters 'disappearing' after changing color to 'normal'

### ISSUE THREAD

**Issue by mbeijen** [convos-chat/convos#665]
**Describe the bug**
When color in text switches to 'normal', a character seems to disappear.

notice the text in the screen shots below: 'losed pull request', 'ushed 1 ommit to blead' 

In weechat, for the same messages, these letters are there. In convos, they're also not in the dom so it is not just a display issue with CSS margins or so.

**To Reproduce**
I don't know how to create IRC messages with color

**Expected behavior**
the text would not get eaten

**Screenshots**
<img width="569" alt="convos-colors" src="https://user-images.githubusercontent.com/659504/148122012-bbdd0b46-4848-4942-b00b-b58e3d646cc6.png">

<img width="786" alt="weechat-colors" src="https://user-images.githubusercontent.com/659504/148122024-3886c520-9df7-4493-8009-a0a514aa5b29.png">

**Environment:**
 - OS: debian testing
 - Browser Firefox
 - IRC server software, name and/or version: irc.perl.org #p5p

**Comment by jhthorsen** [comment]
Thanks for the issue. Unfortunately I don’t know how to fix this bug without a sample text. Can you have a look at the JSON response in the browser dev console from the API and copy paste one of the lines into this issue?

The API request is https://demo.convos.chat/api.html#op-get--connection--connection_id--conversation--conversation_id--messages

**Comment by mbeijen** [comment]
Thanks for explaining about how to capture the messages, that made sense!

I've created a failing test here https://github.com/mbeijen/convos/commit/fb76034d8595100ff66a061f1080c1bdeb2788f6

**Comment by jhthorsen** [comment]
Thanks a lot for the failing test! Hope v6.53 works out.
