### ISSUE TITLE
Image/video previews get collapsed/hidden when opening channel settings

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [convos-chat/convos#688]
**Describe the bug**
When opening channel settings (top right corner), all the visible image/video previews/thumbnails get collapsed/hidden.

**To Reproduce**
1. Go to a channel
2. Paste a link that create an image preview (like an Imgur link)
3. Go to channel settings

**Expected behavior**
Previews should be unaffected by this actions.

**Screenshots**
Small explanatory video [here](https://convos.ptirc.org/file/1/fK4lZAb71fC9QbvN)

**Environment:**
 - OS: Ubuntu
 - Browser Chrome
 - Version 98.0.4758.80 (Official Build) (64-bit)

**Comment by jhthorsen** [comment]
I think this was fixed by accident in one of the recent changes, since I cannot reproduce it anymore.
