### ISSUE TITLE
When scrolled up, we can't close channel settings after opening it

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [convos-chat/convos#689]
**Describe the bug**
When scrolled up, we can't close channel settings after opening it

**To Reproduce**
1. Go to a channel
2. Scroll up a bit in the backlog
3. Click in the `Channel Settings` icon on the top right corner
4. Try to close it clicking in the `X`
5. See error

**Expected behavior**
We should be able to close `Channel Settings` even if scrolled up

**Screenshots**

**Environment:**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 98.0.4758.80 (Official Build) (64-bit)
 - IRC server software, name and/or version: Not applicable

**Comment by jhthorsen** [comment]
Thanks for the issue! This fix will be part of the next release.
