### ISSUE TITLE
Proxy auth behaves not as expected

### ISSUE THREAD

**Issue by max-tet** [convos-chat/convos#704]
**Describe the bug**
When starting Convos with the proxy auth feature, there is still the sign-in screen.

**To Reproduce**
1. Start Convos like this: `docker run --rm -p 8080:3000 -e CONVOS_PLUGINS=Convos::Plugin::Auth::Header -e CONVOS_ADMIN=admin@example.com -e CONVOS_AUTH_HEADER=X-Ptl-User convos/convos:v7.00`
2. Set your browser to send the header value `x-ptl-user=admin@example.com` using e.g. a suitable browser plugin.
3. Navigate to `localhost:8080`
4. You are faced with the initial registration view: As you are the first user, you do not need any invitation link. Just fill in the form below, hit "Sign up" to start chatting.

**Expected behavior**
I expect to be logged-in, i.e. to see no login or registration screen. Convos should behave as if there is an existing user session.

**Environment:**
 - OS: Arch Linux
 - Browser: firefox
 - Version 7.00

**Comment by jhthorsen** [comment]
Does this browser plugin also send the header for WS requests? Please look in the console to see if the header is present for the WebSocket request to "/events".

**Comment by max-tet** [comment]
Seem so. This is the Websocket request:
```
GET /events HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://localhost:8080
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: azSXXXXX
Connection: keep-alive, Upgrade
Cookie: csrftoken=25m5YXXXX; prefsHttp={}; token=t.hQ6nXXXX; grist_core=s%3Ag-eNHNiYBaEXXXX; grist_core_status=S; org.cups.sid=5f6a7eeXXXX; _rails_session=KTEAFZ6XXXXX; sessionid=1cwi23eXXX; express_sid=s%3A7wkXXXX; JSESSIONID=14C28E47XXX; convos=eyJjc3XXXX; convos_js=eyJXXXX
Sec-Fetch-Dest: websocket
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-origin
x-ptl-user: admin@example.com
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

> Sidenote: This sounds like a very scary setup, since anyone with access to the server can create users afterwards. The correct way to set it up is through a reverse proxy.

Yes, absolutely! This was only for testing and reproducing the error. The real setup has an isolated network and a Traefik proxy as the only way to access it.

**Comment by jhthorsen** [comment]
That was very sloppy testing from my side: Some endpoints were trying to lookup the "user" object from other locations than what https://github.com/convos-chat/convos/blob/main/t/plugin-auth-header.t tested. This means that "Header" plugin in v7.00 did not work.

I've fixed the bug and added more tests now. This is part of v7.01.

**Comment by max-tet** [comment]
Works like a charm, thank you for the quick reaction!

**Comment by jhthorsen** [comment]
Thank you for confirming 👍
