### ISSUE TITLE
Leave (or dismiss) wrong channel

### ISSUE THREAD

**Issue by dex2000** [convos-chat/convos#724]
I have tried to enter an password protectet channel with /join #channel password.
That doesnt worked (i have found out later how to do) but the wrong channel is in my channel list as "#channel password" 
How to remove this channel from the list? /part doesnt works

**Comment by PeGaSuS-Coder** [comment]
> I have tried to enter an password protectet channel with /join #channel password.
> That doesnt worked (i have found out later how to do) but the wrong channel is in my channel list as "#channel password"

I've just tried to do `/join  #test 2` and it joined channel `#test` ignoring the  `2`.
How did you mannaged to join a channel with spaces in its name? :thinking:

> How to remove this channel from the list? /part doesnt works

Just hover over the icon near the channel name and it should turn into a `settings` icon (sort of  a cogwheel).

Hope this help.

**Comment by jhthorsen** [comment]
@dex2000: could it be that you’re running a very old version of Convos?

**Comment by dex2000** [comment]
thx for feedback, sry for delay.

We are running 6.37 will contact admin to update it.

**Comment by jhthorsen** [comment]
According to the change log, jointing a password protected channel should be fixed in 6.22… I’ll still hold off the investigation until further notice.

**Comment by jhthorsen** [comment]
I'm guessing this will be fixed with an update.
