### ISSUE TITLE
Loading user data failed: The operation is insecure.

### ISSUE THREAD

**Issue by Sonic3R** [convos-chat/convos#727]
**Describe the bug**

**To Reproduce**
1. Go to https://convos.atmegatron.club/login
2. See error and cannot login or something

**Expected behavior**
Expect to be able to login

**Screenshots**
![image](https://user-images.githubusercontent.com/6311947/163354323-fe8e53c3-ac41-43b0-808a-9b41cabadeef.png)

![image](https://user-images.githubusercontent.com/6311947/163354602-3e467295-4d0d-448b-a978-91498375cd25.png)

**Environment:**
 - OS: Ubuntu 20.04.3
 - Browser: Firefox, Chrome, Edge

**Additional context**
I got error:

```
Loading user data failed: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

I setup CONVOS_REVERSE_PROXY=1 before starting service in order to enable it

**Comment by jhthorsen** [comment]
Please look through https://convos.chat/doc/faq and join #convos on https://libera.chat/ for more support.
