### ISSUE TITLE
Loading user data failed: Could not connect.

### ISSUE THREAD

**Issue by 13MrBlackCat13** [convos-chat/convos#745]
OS: Debian 10
Error: Loading user data failed: Could not connect.
I run the application with `./script/convos daemon -l http://*:9005`, I made a config in nginx
nginx config:
``` 
server {
    server_name chat.domain.tld;
    listen 85.25.134.45:443 ssl http2;

    ssl_certificate "/opt/psa/var/certificates/scfM9hwSR";
    ssl_certificate_key "/opt/psa/var/certificates/scfM9hwSR";
    add_header Strict-Transport-Security "max-age=60; includeSubDomains" always;
    
    location / {
        proxy_pass http://127.0.0.1:9005;
    }
}
```
![mrblackcatdev 2022-05-26 at 14 02 42in Safari](https://user-images.githubusercontent.com/69348201/170484222-98ecb531-6abe-4bd4-ace8-b09b2ed62922.png)

**Comment by jhthorsen** [comment]
You can find a working configuration here: https://convos.chat/doc/reverse-proxy
