### ISSUE TITLE
SASL Support for External Certiticates

### ISSUE THREAD

**Issue by a-diker** [convos-chat/convos#752]
Currently the issue is that the application thinks that  SASL Support is SASL Username + password, 
but now in days SASL uses Exerntal certificates for example tor, can this feature be added or I am glad to help!

**Comment by a-diker** [comment]
How do you do that? Cannot find any guide on doing this seems like it's
unsupported to generate the certificate?

**Comment by a-diker** [comment]
An example is you cannot use tor with SASL plain for Brite force attacks
the server require you use an cert but that cannot be added

You can enter a username and password [PLAIN] butnusing a certificate is
currently not supported by Limechat

**Comment by jhthorsen** [comment]
https://convos.chat/blog/2021/12/23/connecting-to-libera-from-digitalocean

**Comment by a-diker** [comment]
That's not using the client that's using a separate client on a web app

**Comment by jhthorsen** [comment]
I don't understand "That's not using the client that's using a separate client on a web app".

**Comment by jhthorsen** [comment]
Looks like this issue has gone stale.

**Comment by PeGaSuS-Coder** [comment]
I could be wrong, but I believe they're asking for a way to upload/use an already generated certificate.
So it would be used every time without generating new certs for each connection.
That way if we need to reinstall Convos, etc, logins won't break due to the new generated cert.

**Comment by jhthorsen** [comment]
The certificates are stored in $CONVOS_HOME, so they can be replaced. Just not from the web gui.
