### ISSUE TITLE
Arch dependencies listing

### ISSUE THREAD

**Issue by Pound-Hash** [convos-chat/convos#796]
**Is your feature request related to a problem? Please describe.**
Installation fails without certain needed dependencies (in my case `perl-io-socket-ssl`), which aren't documented [here](https://convos.chat/doc/faq#is-convos-supported-on-my-system).

**Describe the solution you'd like**
The docs could be updated with needed dependencies for Arch users.

**Describe alternatives you've considered**
I tried the dependencies listed for other distros and was fortunate to find the one I needed there: `perl-io-socket-ssl`

**Comment by jhthorsen** [comment]
I'm not familiar with Arch, so I would very much appreciate a PR against https://github.com/convos-chat/www.convos.chat/blob/main/doc/faq.md#is-convos-supported-on-my-system 👍

**Comment by jhthorsen** [comment]
Closing this issue, since the patch needs to be applied to "convos-chat/www.convos.chat".

**Comment by marcusramberg** [comment]
I use Arch btw. Can look into aur packaging.

**Comment by jhthorsen** [comment]
@marcusramberg: What is the status here?

**Comment by jhthorsen** [comment]
Looks like this is a stale issue.
