### ISSUE TITLE
Files not actually being deleted

### ISSUE THREAD

**Issue by Mar0xy** [convos-chat/convos#797]
**Describe the bug**
I have noticed that when deleting a file it does remove the json file but leaves the .data file behind which allows me to still view the file by adding it's extension even though everything should be deleted

**To Reproduce**
1. Go to Files
2. Select Files
3. Click "Delete Selected Files"

**Expected behavior**
The files should be fully deleted (the json and the data file)

**Screenshots**
![image](https://user-images.githubusercontent.com/8841466/198868851-63782b93-9b0d-4c04-88a5-d332db7622d9.png)
![image](https://user-images.githubusercontent.com/8841466/198868859-e225783e-9416-4d05-bcc7-883639d5ce88.png)
![image](https://user-images.githubusercontent.com/8841466/198868869-4e7eb902-028a-4955-ba9e-c4da85ae382b.png)

**Environment:**
 - Browser: Firefox
 - Convos Version: 7.06
 - Docker Container

**Comment by jhthorsen** [comment]
That was a silly oversight 😞 

I can't seem to reproduce that you can actually access the files by using the extension though, but either way the deletion is fixed in "main" now.
