### ISSUE TITLE
Blank windows after clicking 'Users' settings

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [convos-chat/convos#798]
**Describe the bug**
After clicking on the `Users` settings, all chat/settings become blank until we refresh the page while in another chat/setting other than `Users`

**To Reproduce**
1. Go to `Users` setting
2. Click on any other setting/chat
3. All windows are blank

**Expected behavior**
All windows should display their content.

**Screenshots**
Screencast showing the issue:
[Users-bug.webm](https://user-images.githubusercontent.com/25697531/198904170-689471b6-6285-49b7-832d-3d5e35bc0237.webm)

**Environment:**
 - OS: Ubuntu 22.04
 - Browser: Google Chrome
 - Version: 107.0.5304.87 (Official Build) (64-bit)

**Comment by jhthorsen** [comment]
I noticed that as well on my phone after the release. I also see it on the desktop now in production. Should be easy to fix, but I have some other things I have to take care of first unfortunately 😞

**Comment by jhthorsen** [comment]
I found some time after all 😄 Fixed in v7.09

3c8e68e491d127c001035c7d73b4652acc50daf0
