### ISSUE TITLE
Restrict videos to a certain size in the chat window

### ISSUE THREAD

**Issue by Mar0xy** [convos-chat/convos#801]
**Is your feature request related to a problem? Please describe.**
It is really messy that when someone or you yourself upload a video that it tends to take a lot of space in the chat window so that you have to scroll up a lot just to get back to prior messages or down to get back to recent ones.

**Describe the solution you'd like**
It would be clever to restrict the maximum size of the video element so that it doesn't just take up a lot of space inside the chat window

**Comment by jhthorsen** [comment]
Do you suggest a max-width and/or max-height? I wonder what the "magical" number would be... Maybe max 40% of the chat height? Do you have a screenshot to make the issue clearer visually?

**Comment by Mar0xy** [comment]
> Do you suggest a max-width and/or max-height?

I think both would be good to have in some way. as seen in the GIF

![Peek 2022-10-31 01-04](https://user-images.githubusercontent.com/8841466/198908562-26270764-29a2-4e3d-bba5-963dd8fbf861.gif)

**Comment by jhthorsen** [comment]
Wow! Thanks for the gif. It makes it all much clearer 😮

I wonder how hard it will be to set max-height... Don't have time to look at it at the moment, but this will get fixed one way or another.

**Comment by Mar0xy** [comment]
Yeah, I have realized this issue pretty early when I installed Convos and was surprised no one else showed this as it basically happens with every video.

**Comment by jhthorsen** [comment]
The change will be part of the next release - Hopefully within 24 hours.

**Comment by jhthorsen** [comment]
> Yeah, I have realized this issue pretty early when I installed Convos and was surprised no one else showed this as it basically happens with every video.

I think the reason is that a lot of videos are horizontal and not vertically. At least I've never seen a vertical video in Convos, or I would've noticed.
