### ISSUE TITLE
Bot support for Codeberg.org / Gitea

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#812]
**Is your feature request related to a problem? Please describe.**
Since Convos is great for self-hosting, it would be nice if it also supported a self-hosting friendly code-forge like Gitea.

**Describe the solution you'd like**
It seems like the Github bot action should be quite similar already, so the same but with Gitea / [Codeberg.org](https://Codeberg.org) support.

**Describe alternatives you've considered**
There are some IRC bots with Gitea support, but it would be nicer to have it all integrated. Thanks!

**Comment by jhthorsen** [comment]
I don't understand in what sense you want Convos to support what you want it to support. Please describe the usecase.

**Comment by poVoq** [comment]
I would like a version of this https://github.com/convos-chat/convos/blob/main/lib/Convos/Plugin/Bot/Action/Github.pm

That works with webhooks from Gitea instead of Github.

**Comment by jhthorsen** [comment]
Looks like they use the same API as Github, so it should just work... That specific plugin is however very specific to Convos and serves more as an example for what is possible. Some users might feel it's incomplete, but it has just the right functionality for #convos 😄

**Comment by poVoq** [comment]
Ok, I guess I will make a PR with a version tested and adapted for Gitea then. Thanks!
