### ISSUE TITLE
Login via LDAP with LLDAP server

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#815]
Edit: Seems like the below is nonsense and after loadig the LDAP auth plugin via the environment variable another bug is happening, see second message.

**Is your feature request related to a problem? Please describe.**
I am trying to set up Convos with a [LLDAP](https://github.com/nitnelave/lldap) server. While otherwise really nice, LLDAP doesn't seem to support Anonymous Bind mode and subsequently I can't log into my Convos instance with LDAP (Invalid email or password error).

Looking at the [LDAP documentation](https://convos.chat/doc/Convos/Plugin/Auth/LDAP) , there doesn't seem to be a way to pass a Simple Bind with DN and password to Convos, however in the the [Perl library documentation](https://convos.chat/doc/Net/LDAP) looks like that it supported (see line 22pp in the Synopsis).

Edit: To be honest I am new to LDAP and might be messing something up. But other LLDAP [example configs](https://github.com/nitnelave/lldap/tree/main/example_configs) require to pass user credentials for an LDAP user with higher access rights, before they allow authenticating a normal user. I think that is called BindDN mode or so.

**Describe the solution you'd like**
To allow simple LDAP access with a LLDAP server it would be great if this could be added as an environment variable setting.

**Additional context**
Edit: I am using the official stable Docker image. Is it possible that the LDAP plugin is not enabled on that?

On a side note: Since LDAP allows choosing a user ID (uid) only and the full DN in LDAP is not necessarily an email address, maybe the input field could allow logging with user name or email (and be renamed accordingly)? A LLDAP filter to allow both would look like this: `(&(objectClass=person)(|(uid=%[1]s)(mail=%[1]s)))`

**Comment by poVoq** [comment]
Looks like the error is actually something else.

After adding `CONVOS_PLUGINS=Convos::Plugin::Auth::LDAP` as an environmental variable I now get the following error on login: `Can't locate object method "email" via package "Mojo::Promise"`

**Comment by jhthorsen** [comment]
> Edit: Seems like the above is nonsense and after loadif the LDAP auth plugin via the environment variable another bug is happening, see second message.

What do you mean with "above" ?

> there doesn't seem to be a way to pass a Simple Bind with DN and password

The Convos documentation is lacking there, but you can use this environment variable:

```
CONVOS_AUTH_LDAP_URL=ldap://localhost:389?password=MyS3cret
```

> Is it possible that the LDAP plugin is not enabled on that

It's present, but not enabled. You have to enable it yourself with the environment variable that you added in your second comment.

**Comment by poVoq** [comment]
Sorry, I meant the below.

Maybe I am missing something, but only a password? What username will be used?

And anyway, see the second message. After loading the plugin it still fails. Do you think that might be a bug or am I still configurating something wrong?

Thanks for the help.

**Comment by jberger** [comment]
The query parameters are transformed into a hash and the url and hash are passed to the [Net::LDAP constuctor](https://metacpan.org/dist/perl-ldap/view/lib/Net/LDAP.pod#new-(-HOST,-OPTIONS-))

**Comment by poVoq** [comment]
Well that doesn't clarify anything though.

Looking at the ldap login debug log posted above and going by the bugfix @jhthorsen did, the problem seems to be that my user and password are not accepted as correct.

Given that the LDAP user does not exist yet in Convos my current guess is that the LDAP auth silently fails somewhere and the fallback to the non-LDAP auth (that is working for existing users) returns a wrong email or password error as the user I am trying to log in with only exists in the LDAP backend.

**Comment by poVoq** [comment]
Ah looks like with LLDAP verbose logging I am getting a hint (actual user replaced with `user@example.com`):
```
2023-01-10T18:13:39.267121011+00:00 INFO     LDAP session [ 110µs | 39.39% / 100.00% ]
2023-01-10T18:13:39.267339254+00:00 INFO     ┕━ LDAP request [ 66.8µs | 52.07% / 60.61% ]
2023-01-10T18:13:39.267349334+00:00 DEBUG       ┝━ 🐛 [debug]:  | msg: LdapMsg { msgid: 8, op: BindRequest(LdapBindRequest { dn: "uid=user,dc=example,dc=com", cred: Simple("********") }), ctrl: [] }
2023-01-10T18:13:39.267352398+00:00 DEBUG       ┝━ do_bind [ 9.41µs | 8.54% ]
2023-01-10T18:13:39.267355679+00:00 DEBUG       │  ┕━ 🐛 [debug]: DN: uid=user,dc=example,dc=com
2023-01-10T18:13:39.267372701+00:00 DEBUG       ┕━ 🐛 [debug]:  | response: BindResponse(LdapBindResponse { res: LdapResult { code: NamingViolation, matcheddn: "", message: "Unexpected DN format. Got \"uid=user,dc=example,dc=com\", expected: \"uid=id,ou=people,dc=example,dc=com\"", referral: [] }, saslcreds: None })
```
So it seems like the request from Convos is missing a `ou=people`?

**Comment by poVoq** [comment]
Passing it via `CONVOS_AUTH_LDAP_URL="ldap://localhost:3890?ou=people` doesn't seem to work, so I think this is a bug in the LDAP auth plugin as the `ou=people` seems required by the LDAP specs?

**Comment by poVoq** [comment]
Got it to work via `CONVOS_AUTH_LDAP_DN="uid=%uid,ou=people,dc=%domain,dc=%tld"`

But it still fails on first login attempt with the same error. I think it needs to create the user Convos side first. On a retry it works with LLDAP.

**Comment by jhthorsen** [comment]
You can also activate verbose logging on the Convos side using `CONVOS_LOG_LEVEL=debug` (or even trace)

> But it still fails on first login attempt with the same error. I think it needs to create the user Convos side first. On a retry it works with LLDAP.

That's strange, since it should create the user on the Convos side on registration. Maybe you can provide the debug output after setting the environment variable mentioned above. The debug output should contain something like:

```
[LDAP/user@example.com] code=X, exists=yes"
```

**Comment by poVoq** [comment]
I'll try that tomorrow and comment on the new specific bug-report.
