### ISSUE TITLE
Option to join new video chat with Jitsi Meet

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#820]
**Is your feature request related to a problem? Please describe.**
Right now it seems like the video room URL is constructed from the IRC channel and network name, meaning that the link shared is always to the same video room on Jitsi Meet. This is useful for some cases, but not so useful for others.

**Describe the solution you'd like**
When trying to share a video chat room, a modal should be shown asking the user if they want to join the default channel room (current behaviour) or create a new video room with a random url and share that with the IRC chat instead.

**Additional context**
Having this conditional modal would also avoid people accidentally sharing links to video room by mis-clicking, as currently there is no confirmation dialogue at all.

**Comment by jhthorsen** [comment]
I'm not going to implement that. The reason why it's the same is that you are in the same room and therefor the video button have to join the same meeting. Or else there's no way for Convos to know which room to join.

The "mis-clicking" issue was much greater before, but I haven't really seen it recently after it was moved to the submenu.

If I knew that this issue would affect many users, I would consider doing some changes, but I don't think that is the case.

**Comment by poVoq** [comment]
> Or else there's no way for Convos to know which room to join.

But the link to the room is shared in the chat, so anyone can just click on it and join.

Sometimes it is desirable to have multiple parallel chats as break out rooms, so I think having this as an second option would be really nice.
