### ISSUE TITLE
Option to minimize networks and user settings?

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#825]
**Is your feature request related to a problem? Please describe.**
When connected to multiple IRC networks and channels the list on the left side gets very long especially also because all the user setting links are always shown there.

**Describe the solution you'd like**
It would be nice if there was a small icon to collapse the network to a single line to temporarily hide all the channels in it. Similarly the user settings could be also temporarily collapsed by a button or so.

Thanks!

**Comment by jhthorsen** [comment]
This should be fixed by @mostlyvirtual in #840.
