### ISSUE TITLE
Version check wrong behavior

### ISSUE THREAD

**Issue by TehPeGaSuS** [convos-chat/convos#829]
**Describe the bug**
When you click on `Settings > Check for updates` and you're already running the latest version, Convos will say `Convos vXXX is available.` which corresponds to the same version we're using.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Check for updates' while using the latest version
3. See error

**Expected behavior**
Convos should say `You're already running the latest version` or tell something like `New version available: vXXX` if there's a newer version

**Screenshots**  

[convos_version.webm](https://user-images.githubusercontent.com/25697531/225762273-43b94252-282f-4d97-bb56-6241fab7563a.webm)

**Environment:**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Chrome
 - Version: Version 111.0.5563.64 (Official Build) (64-bit)
 - IRC server software, name and/or version: N/A

**Comment by jhthorsen** [comment]
Took one year to fix this... #dadlyfe
