### ISSUE TITLE
7.16 version mismatch

### ISSUE THREAD

**Issue by zakame** [convos-chat/convos#858]
Hi, thanks for this great piece of Perl software! 🎉 

While packaging updates for https://github.com/NixOS/nixpkgs/pull/262104 I just noticed that `lib/Convos.pm` in the 7.16 release still lists `7.15` as its `$VERSION`: https://github.com/convos-chat/convos/blob/v7.16/lib/Convos.pm#L16

**Comment by jhthorsen** [comment]
v7.16 was really just a test-tag to see if the docker build actions would do the right thing. The plan was to release 8.00 the next day, but life came in the way.

I hope this is fixed now.

**Comment by zakame** [comment]
Thanks for clarifying @jhthorsen ! 🎉
