### ISSUE TITLE
Figure out and fix "unknown/unknown" architecture for arm/v7

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#864]
**Describe the bug**
https://github.com/convos-chat/convos/pkgs/container/convos/146201501?tag=alpha shows "unknown/unknown" instead of "linux/arm/v7". At least that's what I would expect?

**Additional context**
This happened after https://github.com/convos-chat/convos/pull/863 was merged. It was *not* fixed, even after merging https://github.com/convos-chat/docker-base/pull/24 and rebuilding the Convos image.

Got any ideas @cadubentzen?

**Comment by cadubentzen** [comment]
No idea yet. In convos-base, linux/arm/v7 is listed at least: https://github.com/convos-chat/docker-base/pkgs/container/convos-base/146201108?tag=main

**Comment by cadubentzen** [comment]
Ok the problem is that I didn't realize there were two workflows for alpha.yml on main and docker.yml for the tagged releases. My bad! #865 should fix it.

**Comment by jhthorsen** [comment]
I think it still says unknown...?

https://github.com/convos-chat/convos/pkgs/container/convos/146718615?tag=alpha

**Comment by cadubentzen** [comment]
Wasn't `unknown/unknown` already there? I also see it for the stable tag published 2 weeks ago: https://github.com/convos-chat/convos/pkgs/container/convos/143101376?tag=stable

I also see that my own packages also have `unknown/unknown`, and is reported behavior here https://github.com/orgs/community/discussions/45969
