### ISSUE TITLE
Docs: broken link in the "Getting started" page

### ISSUE THREAD

**Issue by OniriCorpe** [convos-chat/convos#883]
**Describe the bug**
The link about the `EV` module is broken in the following page: https://convos.chat/doc/start#optional-modules

**To Reproduce**

1. Go to the docs, page "Getting started", § Optional modules
2. Click on the link explaining why `EV`
3. Get a 404

**Expected behavior**
Correct link is `https://docs.mojolicious.org/Mojolicious/Guides/FAQ#Why-doesnt-Mojolicious-have-any-dependencies`

**Screenshots**
N/A

**Environment:**
N/A

**Additional context**
N/A

**Comment by jhthorsen** [comment]
Thanks 👍  Should be fixed in main (not yet available online)

Please open issues related to the website in https://github.com/convos-chat/www.convos.chat instead.
