### ISSUE TITLE
Convos does not work properly when installed on a path

### ISSUE THREAD

**Issue by OniriCorpe** [convos-chat/convos#884]
**Describe the bug**
Convos does not work properly when installed on a path, because it tries to join `/api` and not `/convos-path/api`

**To Reproduce**
1. Install Convos on a `/path`, like `https://example.com/convos`
2. Try to login
3. The login fails
4. See error in the console saying that Convos tried to join `https://example.com/api`

**Expected behavior**
Convos calls it's api following it's current path, like `https://example.com/convos/api`

**Environment:**
 - OS: YunoHost on Debian Bullseye / `Linux 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 x86_64 GNU/Linux`
 - Reverse proxied by nginx
 - `Environment="CONVOS_REQUEST_BASE=https://DOMAIN/PATH"` in the systemd config
 - Browser: Firefox 123.0
 - Version: 8.05

**Additional context**
I'm trying to package Convos [for YunoHost](https://yunohost.org/whatsyunohost), and during my various tests i saw this bug

**Comment by jhthorsen** [comment]
I don't know what YunoHost is, but could it be that the version is just way too old?

**Comment by jhthorsen** [comment]
There's even a test for CONVOS_REQUEST_BASE, so it should work.

https://github.com/convos-chat/convos/blob/b1bf09ce732958cbea286d64702763cf13b61d5b/t/web-base-url.t#L46

**Comment by jhthorsen** [comment]
I think you forgot to set CONVOS_REVERSE_PROXY.

https://convos.chat/doc/reverse-proxy#start-convos-with-correct-environment-variables

**Comment by arosell-hsco** [comment]
This is still an issue, I just tried today, and it doesn't work, it either points to /api instead of /path/api or it gets into a loop and it starts to rewrite the baseParth in api as /path/path/path/path/api
