### ISSUE TITLE
Convos Docker :stable tag point to an old 7.15 version

### ISSUE THREAD

**Issue by mariushosting** [convos-chat/convos#886]
The latest version seems to be version v8.05 but the :stable Docker tag install the outdated v7.15 version instead of v8.05 version
Can you please check this @jhthorsen ?

**Comment by marcusramberg** [comment]
@mariushosting Note that we switched to github container registry with 8.0, so the dockerhub images are deprecated. https://github.com/orgs/convos-chat/packages/container/package/convos

**Comment by mariushosting** [comment]
> @mariushosting Note that we switched to github container registry with 8.0, so the dockerhub images are deprecated. https://github.com/orgs/convos-chat/packages/container/package/convos

Thank you for the info! Appreciate it Marcus!

**Comment by mariushosting** [comment]
closed
